export * as arrowDecline from '#/icons/arrow_decline.svg';
export * as  arrowGrowth from '#/icons/arrow_growth.svg';
export * as  arrowLeft from '#/icons/arrow_left.svg';
export * as  arrowMaintain from '#/icons/arrow_maintain.svg';
export * as  arrowRight from '#/icons/arrow_right.svg';
export * as arrowUp from '#/icons/arrow_up.svg';
export * as book from '#/icons/book.svg';
export * as  circle from '#/icons/circle.svg';
export * as  female from '#/icons/female.svg';
export * as  home from '#/icons/home.svg';
export * as mail from "#/icons/mail.svg";
export * as  male from '#/icons/male.svg';
export * as  run from '#/icons/run.svg';
export * as  settings from '#/icons/settings.svg';
export * as  sleep from '#/icons/sleep.svg';
export * as  statistics from '#/icons/statistics.svg';
export * as  user from '#/icons/user.svg';
export * as  walk from '#/icons/walk.svg';

